# FIX EXTRA HIGH PROCESSOR LOAD
SHOW FULL PROCESSLIST;
EXPLAIN SELECT * FROM table_name WHERE column_name = 'some_filter';
type=ALL, key=NULL, rows=some_high_number ⇒ full table scan
ALTER TABLE table_name
  ADD INDEX idx_column_name (column_name);
type=ref, key=idx_column_name, rows=1 ⇒ index table scan

# CREATE 100 ROWS TABLE
CREATE TABLE IF NOT EXISTS numbers_100 (
    num INT PRIMARY KEY
);

INSERT INTO numbers_100 (num)
SELECT (a.n + (b.n - 1) * 10) AS num
FROM (
  SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
  UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
) a
CROSS JOIN (
  SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
  UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
) b
ORDER BY num;

SELECT num FROM numbers_100;
